tinyows:
  image: camptocamp/tinyows:${DOCKER_TAG}
  environment:
    TINYOWS_CATCH_SEGV: "1"
    SEGFAULT_SIGNALS: "all"
  links:
    - db
  ports:
    - 8380:8080
  volumes_from:
    - acceptance_config
  user: www-data

db:
  image: camptocamp/postgres:11.4
  environment:
    POSTGRES_USER: www-data
    POSTGRES_PASSWORD: www-data
    POSTGRES_DB: test
  ports:
    - 15432:5432
  volumes_from:
    - acceptance_config

acceptance_config:
  image: camptocamp/tinyows_acceptance_config:${DOCKER_TAG}
