[tool.black]
line-length = 110
target-version = ["py39"]

[tool.poetry]
name = "docker-tinyows"
version = "0.0.0"
description = "Docker image for TinyOWS"
authors = ["Camptocamp <info@camptocamp.com>"]
