---
name: Continuous integration

on:
  push:

env:
  DOCKER_BUILDKIT: "1"

jobs:
  main:
    runs-on: ubuntu-20.04
    name: Continuous integration
    timeout-minutes: 10

    steps:
      # Versions
      - run: docker --version
      - uses: actions/checkout@v3

      - run: make pull
      - run: make build
      - run: make acceptance

      - uses: camptocamp/initialise-gopass-summon-action@v1
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
          patterns: docker
        if: github.repository == 'camptocamp/docker-tinyows'

      - name: Publish to Docker hub
        run: ci/publish
        if: |
          github.repository == 'camptocamp/docker-tinyows'
          && env.HAS_SECRETS == 'HAS_SECRETS'
          && ! contains(github.ref_name, '/')
