---

name: Rebuild

on:
  schedule:
    - cron: "30 2 * * *"

jobs:
  main:
    runs-on: ubuntu-18.04
    name: Rebuild
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        branch:
          - master

    env:
      MAIN_BRANCH: master
      MAJOR_VERSION: 2.5
      CI: true
      PATH: /bin:/usr/bin:/usr/local/bin:/home/runner/.local/bin
      SUMMON_PROVIDER: /usr/local/bin/gopass

    steps:
      # Versions
      - run: docker --version
      - uses: actions/checkout@v1
        with:
          ref: ${{ matrix.branch }}

      - run: make pull
      - run: make build
      - run: make acceptance

      - uses: camptocamp/initialise-gopass-summon-action@v1
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GITHUB_GOPASS_CI_TOKEN}}
        if: github.repository == 'camptocamp/docker-tinyows'
      - run: mkdir -p ~/.docker
      - run: |
          summon --yaml '
            TOKEN: !var gs/ci/dockerhub/token
          ' bash -c 'envsubst < ci/docker-config.json.tmpl > ~/.docker/config.json'
        if: github.repository == 'camptocamp/docker-tinyows'
      - name: Publish to Docker hub
        run: ci/publish ${{ matrix.branch }}
        if: github.repository == 'camptocamp/docker-tinyows'
