name: Rebuild

on:
  schedule:
    - cron: 30 2 * * *

jobs:
  main:
    runs-on: ubuntu-22.04
    name: Rebuild
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        branch:
          - master

    steps:
      - run: docker system prune --all --force
      # Versions
      - run: docker --version
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - run: make pull
      - run: make build
      - run: make acceptance

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
          patterns: docker

      - name: Publish to Docker hub
        run: ci/publish ${{ matrix.branch }}
